export const translations = Object.freeze({
  en: {
    app: { name: 'Smart Steam Unlocker', language: 'Language', english: 'English', arabic: 'العربية', windowControls: 'Window controls', minimize: 'Minimize', maximize: 'Maximize', restore: 'Restore', close: 'Close', steamId: 'Steam ID: {id}' },
    nav: { dashboard: 'Dashboard', library: 'Library', achievements: 'Achievements', tradingCards: 'Trading Cards', integrity: 'Achievement Integrity', settings: 'Settings', navigation: 'Navigation', selectedGame: 'Selected Game' },
    common: { cancel: 'Cancel', confirm: 'Confirm', close: 'Close', clear: 'Clear', resume: 'Resume', pause: 'Pause', stop: 'Stop', start: 'Start', loading: 'Loading…', retry: 'Try Again', selected: '{count} Selected', noDescription: 'No description available.', hiddenAchievement: 'Hidden Achievement', unlock: 'Unlock', relock: 'Relock', failed: 'Failed', verified: 'Verified', completed: 'Completed', scheduled: 'Scheduled', inQueue: 'In Queue' },
    mode: { instant: 'Instant Mode', humanized: 'Humanized Mode', original: 'Original', naturalStory: 'Natural / Story Progression', commonToRare: 'Most Common → Rarest', rareToCommon: 'Rarest → Most Common' },
    achievements: {
      title: 'Achievements', viewing: 'Viewing achievements for {game}', selectGame: 'Select a game from your library to browse its achievements.', changeGame: 'Change Game', browseLibrary: 'Browse Library', steamContext: 'Steam context active', progressionMode: 'Achievement progression mode', smartDelay: 'Smart Delay Timer', startQueue: 'Start ({count})', resumeQueue: 'Resume Queue', clearQueue: 'Clear Queue', speed: 'Speed Multiplier', variance: 'Random Variance', fixedTime: 'Use Fixed Custom Time (Manual Override)', baseTime: 'Base Time:', minutes: 'minutes', confirmationPending: 'Steam confirmation pending.', confirmationComplete: 'Steam verification complete.', confirmationAttention: 'Steam confirmation needs attention.', recheck: 'Recheck Steam confirmation', confirming: 'Confirming:', unlocking: 'Unlocking:', selectAllLocked: 'Select All Locked', deselectVisibleLocked: 'Deselect Visible Locked', search: 'Search achievements…', filters: { all: 'All', locked: 'Locked', unlocked: 'Unlocked' }, gridOrder: 'Grid ordered by {mode}. Select locked achievements to include them in a new schedule.', gridFallback: 'Could not calculate the selected Humanized order. The grid remains in Steam source order until ordering can be retried.', fetching: 'Fetching achievements...', syncing: 'Syncing data with Steam servers', loadFailed: 'Could not load achievements', noResults: 'No achievements found', noResultsSub: 'Check if this game supports Steam achievements.', noGame: 'No Game Selected', noGameSub: 'Head to the Library, pick a game, and the app will automatically restart with the correct Steam context to fetch its achievements.', relockRequested: 'Relock requested', relockPending: 'Verification pending', relockTitle: 'Relock achievement?', relockWarning: '“{achievement}” will be returned to the locked state. This changes your Steam achievement state and cannot be undone automatically.', confirmRelock: 'Relock achievement', relockSucceeded: 'Relock succeeded.', relockPendingTitle: 'Relock pending verification.', relockFailed: 'Relock failed.', relockVerified: 'Relock verified. Steam now reports this achievement as locked.', relockRemotePending: 'Steam accepted the relock locally. Remote verification is pending.', relockFailedDetail: 'Relock failed. Steam did not change this achievement.', relockTooltip: 'Return this achievement to its locked state', relockAria: 'Relock {achievement}'
    },
    scheduler: { create: 'Create Schedule', chooseProgress: 'Choose how to progress', pace: 'Set the pace', waiting: 'Waiting for scheduled time', backgroundVerification: 'Background verification', confirming: 'Confirming', unlockSubmitted: 'Unlock submitted', steamAccepted: 'Steam accepted activation', verificationPending: 'Verification pending', verificationComplete: 'Verification complete' },
    integrity: { title: 'Achievement Integrity', scan: 'Scan', analyze: 'Analyze', explain: 'Explain', score: 'Integrity Score', normal: 'Normal', unusual: 'Unusual', highAnomaly: 'High Anomaly', extremeAnomaly: 'Extreme Anomaly', viewEvidence: 'View Evidence' },
    trading: { title: 'Trading Cards', monitoring: 'Monitoring', cardDataAvailable: 'Card data available', dropsExhausted: 'Drops exhausted', statusUnavailable: 'Card status unavailable' },
    settings: { title: 'Settings', subtitle: 'Configure a Steam Web API key to unlock the full game library.', languageTitle: 'Language', languageSub: 'Choose the application language. Arabic uses a right-to-left layout immediately.', apiKey: 'Steam Web API Key', saveKey: 'Save key', replaceKey: 'Replace key', savedSecurely: 'Saved securely', testConnection: 'Test Connection', clearKey: 'Clear key', about: 'About & Credits', repository: 'GitHub Repository', creator: 'Created by Khalid Alotaibi', projectLinks: 'Project links' },
    status: { connected: 'Steam Connected', disconnected: 'Steam Disconnected — Open Steam and restart', recentActivity: 'Recent Activity', noRecent: 'No recent activity reported by Steam' }
  },
  ar: {
    app: { name: 'Smart Steam Unlocker', language: 'اللغة', english: 'English', arabic: 'العربية', windowControls: 'عناصر تحكم النافذة', minimize: 'تصغير', maximize: 'تكبير', restore: 'استعادة', close: 'إغلاق', steamId: 'معرّف Steam: {id}' },
    nav: { dashboard: 'لوحة المعلومات', library: 'المكتبة', achievements: 'الإنجازات', tradingCards: 'بطاقات التداول', integrity: 'سلامة الإنجازات', settings: 'الإعدادات', navigation: 'التنقل', selectedGame: 'اللعبة المختارة' },
    common: { cancel: 'إلغاء', confirm: 'تأكيد', close: 'إغلاق', clear: 'مسح', resume: 'استئناف', pause: 'متوقف مؤقتًا', stop: 'إيقاف', start: 'بدء', loading: 'جارٍ التحميل…', retry: 'حاول مرة أخرى', selected: '{count} محدد', noDescription: 'لا يتوفر وصف.', hiddenAchievement: 'إنجاز مخفي', unlock: 'فتح الإنجاز', relock: 'إعادة قفل الإنجاز', failed: 'فشل', verified: 'تم التحقق', completed: 'مكتمل', scheduled: 'مجدول', inQueue: 'في قائمة الانتظار' },
    mode: { instant: 'الوضع الفوري', humanized: 'محاكاة الإنسان', original: 'الأصلي', naturalStory: 'المحاكاة الطبيعية / تسلسل القصة', commonToRare: 'من الأكثر شيوعًا إلى الأندر', rareToCommon: 'من الأندر إلى الأكثر شيوعًا' },
    achievements: {
      title: 'الإنجازات', viewing: 'عرض إنجازات {game}', selectGame: 'اختر لعبة من مكتبتك لاستعراض إنجازاتها.', changeGame: 'تغيير اللعبة', browseLibrary: 'استعراض المكتبة', steamContext: 'سياق Steam نشط', progressionMode: 'وضع التقدّم في الإنجازات', smartDelay: 'مؤقت التأخير الذكي', startQueue: 'بدء ({count})', resumeQueue: 'استئناف قائمة الانتظار', clearQueue: 'مسح قائمة الانتظار', speed: 'مضاعف السرعة', variance: 'التباين العشوائي', fixedTime: 'استخدام وقت ثابت مخصص (تجاوز يدوي)', baseTime: 'الوقت الأساسي:', minutes: 'دقائق', confirmationPending: 'بانتظار تأكيد Steam.', confirmationComplete: 'اكتمل التحقق من Steam.', confirmationAttention: 'يتطلب تأكيد Steam الانتباه.', recheck: 'إعادة التحقق من تأكيد Steam', confirming: 'جارٍ التحقق:', unlocking: 'جارٍ فتح:', selectAllLocked: 'تحديد كل الإنجازات المقفلة', deselectVisibleLocked: 'إلغاء تحديد الإنجازات المقفلة الظاهرة', search: 'ابحث في الإنجازات…', filters: { all: 'الكل', locked: 'مقفلة', unlocked: 'مفتوحة' }, gridOrder: 'ترتيب الشبكة حسب {mode}. حدّد الإنجازات المقفلة لإضافتها إلى جدول جديد.', gridFallback: 'تعذّر حساب ترتيب محاكاة الإنسان المحدد. ستبقى الشبكة بترتيب Steam الأصلي حتى إعادة المحاولة.', fetching: 'جارٍ جلب الإنجازات…', syncing: 'جارٍ مزامنة البيانات مع خوادم Steam', loadFailed: 'تعذّر تحميل الإنجازات', noResults: 'لم يتم العثور على إنجازات', noResultsSub: 'تحقق مما إذا كانت هذه اللعبة تدعم إنجازات Steam.', noGame: 'لم يتم اختيار لعبة', noGameSub: 'انتقل إلى المكتبة، واختر لعبة، وسيُعاد تشغيل التطبيق تلقائيًا بسياق Steam الصحيح لجلب إنجازاتها.', relockRequested: 'تم إرسال طلب إعادة القفل', relockPending: 'التحقق قيد الانتظار', relockTitle: 'إعادة قفل الإنجاز؟', relockWarning: 'سيُعاد “{achievement}” إلى الحالة المقفلة. يغيّر هذا حالة إنجازك في Steam ولا يمكن التراجع عنه تلقائيًا.', confirmRelock: 'إعادة قفل الإنجاز', relockSucceeded: 'نجحت إعادة القفل.', relockPendingTitle: 'إعادة القفل بانتظار التحقق.', relockFailed: 'فشلت إعادة القفل.', relockVerified: 'تم التحقق من إعادة القفل. يُبلغ Steam الآن أن هذا الإنجاز مقفل.', relockRemotePending: 'وافق Steam على إعادة القفل محليًا. التحقق عن بُعد قيد الانتظار.', relockFailedDetail: 'فشلت إعادة القفل. لم يغيّر Steam هذا الإنجاز.', relockTooltip: 'أعد هذا الإنجاز إلى حالته المقفلة', relockAria: 'إعادة قفل {achievement}'
    },
    scheduler: { create: 'إنشاء جدول', chooseProgress: 'اختر طريقة التقدّم', pace: 'حدّد وتيرة التقدّم', waiting: 'بانتظار الموعد المحدد', backgroundVerification: 'التحقق في الخلفية', confirming: 'جارٍ التحقق', unlockSubmitted: 'تم إرسال طلب فتح الإنجاز', steamAccepted: 'وافق Steam على عملية التفعيل', verificationPending: 'التحقق قيد الانتظار', verificationComplete: 'اكتمل التحقق' },
    integrity: { title: 'سلامة الإنجازات', scan: 'فحص', analyze: 'تحليل', explain: 'التفسير', score: 'درجة سلامة الإنجازات', normal: 'طبيعي', unusual: 'غير معتاد', highAnomaly: 'شذوذ مرتفع', extremeAnomaly: 'شذوذ شديد', viewEvidence: 'عرض الأدلة' },
    trading: { title: 'بطاقات التداول', monitoring: 'المراقبة', cardDataAvailable: 'بيانات البطاقات متاحة', dropsExhausted: 'تم استنفاد البطاقات المتبقية', statusUnavailable: 'حالة البطاقات غير متاحة' },
    settings: { title: 'الإعدادات', subtitle: 'اضبط مفتاح Steam Web API لفتح مكتبة الألعاب الكاملة.', languageTitle: 'اللغة', languageSub: 'اختر لغة التطبيق. يُطبَّق تخطيط العربية من اليمين إلى اليسار فورًا.', apiKey: 'مفتاح Steam Web API', saveKey: 'حفظ المفتاح', replaceKey: 'استبدال المفتاح', savedSecurely: 'تم الحفظ بأمان', testConnection: 'اختبار الاتصال', clearKey: 'مسح المفتاح', about: 'حول وحقوق النشر', repository: 'مستودع GitHub', creator: 'أنشأه خالد العتيبي', projectLinks: 'روابط المشروع' },
    status: { connected: 'Steam متصل', disconnected: 'Steam غير متصل — افتح Steam وأعد تشغيل التطبيق', recentActivity: 'النشاط الأخير', noRecent: 'لا يوجد نشاط حديث مُبلغ عنه من Steam' }
  },
});
